# This Action should fail because there is no controlrepo here.
# What I am interested in is if it fails because it can't find the Puppet gem versions.

name: unit-tests

# Controls when the workflow will run
on: 
  - push
  - pull_request
  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      - name: action-controlrepo-pdk-tests-6
        # You may pin to the exact commit or the version.
        # uses: puppets-epic-show-theatre/action-pdk-validate@31b5407676af16b690b2b8c54c0767af72fcc34f
        uses: newcastleuniversity/action-controlrepo-pdk-tests@1.0.0
        with:
          # A string indicating the Puppet version to validate against.
          # Use one of "6.29.0" or "7.22.0", see https://tickets.puppetlabs.com/browse/PUP-11722
          puppet-version: "6.29.0"
          # A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".
          pe-version: # optional
          site-module-path: site

      - name: action-controlrepo-pdk-tests-7
        # You may pin to the exact commit or the version.
        # uses: puppets-epic-show-theatre/action-pdk-validate@31b5407676af16b690b2b8c54c0767af72fcc34f
        uses: newcastleuniversity/action-controlrepo-pdk-tests@1.0.0
        with:
          # A string indicating the Puppet version to validate against.
          # Use one of "6.29.0" or "7.22.0", see https://tickets.puppetlabs.com/browse/PUP-11722
          puppet-version: "7.22.0"
          # A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".
          pe-version: # optional
          site-module-path: site

